splash = false

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/Wallpapers/forgeworld-secondary.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/Wallpapers/forgeworld-main.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/.config/hypr/Wallpapers/forgeworld-error.png
    fit_mode = cover
}