general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
    fail_timeout = 2000
}

animations {
    enabled = true
    bezier = forge, 0.23, 1, 0.32, 1
    animation = fade, 1, 2, forge
    animation = inputField, 1, 2, forge
}

background {
    monitor =
    path = screenshot
    color = rgba(0d0d0dff)

    blur_passes = 3
    blur_size = 8
    brightness = 0.45
    vibrancy = 0.15
    vibrancy_darkness = 0.1
}

label {
    monitor =
    text = $TIME
    color = rgba(ff3333ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font Bold

    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = FORGE NODE LOCKED
    color = rgba(d8ccb8ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, 90
    halign = center
    valign = center
}

label {
    monitor =
    text = User: $USER
    color = rgba(b08d57ff)
    font_size = 14
    font_family = JetBrainsMono Nerd Font

    position = 0, 55
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 360, 58
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.18
    dots_center = true

    inner_color = rgba(0d0d0dcc)
    outer_color = rgba(8b0000ff) rgba(c1121fff) 45deg
    font_color = rgba(d8ccb8ff)

    check_color = rgba(b08d57ff)
    fail_color = rgba(ff3333ff)
    capslock_color = rgba(ff3333ff)

    placeholder_text = <i>Authentication Rite...</i>
    fail_text = <i>Access denied: $FAIL</i>

    fade_on_empty = false
    rounding = 0

    position = 0, -30
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = rgba(8b0000ff)
    font_size = 12
    font_family = JetBrainsMono Nerd Font

    position = 0, -95
    halign = center
    valign = center
}

label {
    monitor =
    text = The Machine Spirit awaits authentication.
    color = rgba(b08d57ff)
    font_size = 13
    font_family = JetBrainsMono Nerd Font

    position = 0, -140
    halign = center
    valign = center
}